### ISSUE TITLE
 在Origin OS 5上无法使用

### ISSUE THREAD

**Issue by lovexxx** [chenjunyu19/MediaVolume#3]
也无法设置权限（显示“未请求任何权限”）
![Screenshot_20241117_174151](https://github.com/user-attachments/assets/97120ff0-bcbc-46cf-86b2-fb938d5d9c37)

**Comment by chenjunyu19** [comment]
此应用在清单中仅声明了以下 1 个权限。

```
android.permission.MODIFY_AUDIO_SETTINGS
更改您的音频设置
允许该应用修改全局音频设置，例如音量和用于输出的扬声器。
```

这个权限属于[安装时权限中的一般权限](https://developer.android.google.cn/guide/topics/permissions/overview?hl=zh-cn#normal)，系统会在安装应用时自动授予，**不需要**也**不能够**在运行时请求用户授权，因此你不会在应用信息页面看到这类权限。

合理猜测你无法正常使用的原因是你所使用的定制 Android 系统剥夺了该权限，但是我没有运行 `Origin OS 5` 的设备，无法帮你验证。你可以尝试在诸如“手机管家”这类系统自带的“优化软件”中手动授予诸如“自启动”、“关联启动”、“始终允许”等权限。

**Comment by lovexxx** [comment]
![Screenshot_20241125_105747](https://github.com/user-attachments/assets/c085b327-985a-473e-b2fc-f949b77860fe)
已全开权限，仍无法生效

**Comment by lovexxx** [comment]
> ![Screenshot_20241125_105747](https://private-user-images.githubusercontent.com/28099434/389351277-c085b327-985a-473e-b2fc-f949b77860fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MDQxNjUsIm5iZiI6MTczMjUwMzg2NSwicGF0aCI6Ii8yODA5OTQzNC8zODkzNTEyNzctYzA4NWIzMjctOTg1YS00NzNlLWIyZmMtZjk0OWI3Nzg2MGZlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDAzMDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MjdkNWJlODE5ZThkZTc0NTEyMTE3NDhhZTExYjIwOTJhNGQxNmRhMGQ5MWRlMjE2Y2YzZjQ0YjAxYTQ2YWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IpH-ZcUwlXkVqCnGb_130UOUBunWKpjOdSjh6bLMBic) 已全开权限，仍无法生效

可能是OriginOS5的bug吧
